### ISSUE TITLE
Larger cutout images

### ISSUE THREAD

**Issue by jvansanten** [AmpelProject/FrontEnd#2]
Currently the cutout images are rendered at native size (63x63 pixels), which looks rather small on most screens. There doesn't seem to be a way to set the scale on a canvas element, but another way might be to draw each image pixel into 4 canvas pixels.

**Comment by vbrinnel** [comment]
you could add `style="margin-top: 100;-moz-transform: scale(1.5);"` to the div with id `FITSViewer`

```
<div class="col-md-1 col-md-1 col-sm-1 text-center" id="FITSViewer" style="margin-top: 100;-moz-transform: scale(1.5);">
```

This is compatible with Firefox and Chrome.

<img width="1320" alt="screen shot 2018-12-08 at 12 26 34" src="https://user-images.githubusercontent.com/17532220/49685501-968b5000-fae4-11e8-8a4e-7c8fe9246b6b.png">

**Comment by vbrinnel** [comment]
And you could have plus and minus buttons calling JS functions increasing/decreasing the `-moz-transform: scale` value
